### ISSUE TITLE
[Refactor] User domain refactor 

### ISSUE THREAD

**Issue by hyeonji91** [UMC-Project-Namo/Server#12]
## **Issue : {Task-Type}**
User 도메인에 대한 리펙토링 진행

## **Description**
코드 컨벤션에 맞게 User 도메인 리펙토링 진행

## **Todo**
- [x] presentation 계층 분리 : ui 디렉토리를 사용하여 구현
- [x] application 계층 분리
- [x] Persistence 계층 분리 : dao 디렉토리를 사용하여 구현
- [x] domain model 분리
- [x] Facade 적용
